### ISSUE TITLE
Test tilt / rotation gestures with smaller fiducial markers.

### ISSUE THREAD

**Issue by jasonalderman-valtech** [valtech-sd/spyglass#53]
AC:
- [x] Current markers are 1" x 1", want to test with 1/2" wide (approx.)
- [x] Determine if it's as responsive, if marker gets lost more easily.
~~Figure out best parameters to set to have this work well. (Have not explored AR.js threshholds.)~~ --> Will move this to the story where we actually use the gesture in the scenario
- [x] Create reference video using current gestures with the 1/2" wide markers

**Comment by aolivier** [comment]
Summary of findings:

All videos start with 1 inch marker gesture, then 0.5 marker gesture for comparison

All of the basic rotation movements were "untuned" (as-in thresholds were not perfectly adjusted to make the gesture super easy). So keep that in mind. I can already tell that forward tilt needs to have a lower threshold! This was intended to be performed in a later PR.

- Tilt-forward and tilt-side seem to perform roughly the same at 1 inch and 0.5 inch
- "Twist" (with one marker) performs worse with a smaller marker, because it has a strong tendency to lose the tracking. This was also the hardest gesture for 1 inch marker too, so no big surprise.
- Multi-marker rotation works well on both, and after moving the markers closer as @Danielle suggested, is a lot easier to perform!

[Videos are posted here](https://drive.google.com/drive/folders/1ZtqL4WMTj3dmTwOeFdUuSmi7WAUeQH8p?usp=sharing)
